name: Release

on:
  push:
    branches:
      - main
    tags:
      - "*"

defaults:
  run:
    shell: bash

jobs:
  all:
    name: All

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v3

      - name: Setup macOS/linux
        if: ${{ matrix.os != 'windows-latest' }}
        run: ./setup.sh

      - name: Setup windows
        if: ${{ matrix.os == 'windows-latest' }}
        shell: pwsh
        run: ./setup.ps1

      - name: Install dependencies
        run: npm ci

      - name: Make
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          yarn make
        timeout-minutes: 30

      - name: Make
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          export DEBUG=electron-rebuild
          yarn make --arch ia32
          yarn make --arch x64
        timeout-minutes: 30

      - name: Prepare ...
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          cp "out/make/squirrel.windows/x64/cursor-${{ github.ref_name }} Setup.exe" "out/make/squirrel.windows/x64/cursor-win32-x64-${{ github.ref_name }}-Setup.exe"
          cp "out/make/squirrel.windows/ia32/cursor-${{ github.ref_name }} Setup.exe" "out/make/squirrel.windows/ia32/cursor-win32-ia32-${{ github.ref_name }}-Setup.exe"

      - name: Checking...
        run: |
          ls -l out && ls -l out/make
          npm install -g tree-cli
          (cd out && treee -l 5)
          
      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   if: startsWith(github.ref, 'refs/tags/')
      #   with:
      #     fail_on_unmatched_files: false
      #     files: |
      #       out/make/zip/**/*.zip
      #       out/make/squirrel.windows/x64/cursor-win32-x64-${{ github.ref_name }}-Setup.exe
      #       out/make/squirrel.windows/ia32/cursor-win32-ia32-${{ github.ref_name }}-Setup.exe
      
      - name: Release
        uses: xresloader/upload-to-github-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: >-
            out/make/zip/**/*.zip;
            out/make/deb/**/*.deb;
            out/make/rpm/**/*.rpm;
            out/make/squirrel.windows/**/cursor-win32-*.exe;
          tags: true
          draft: false
          overwrite: true
